### ISSUE TITLE
Remove the node "distinctor" from the heuristic workflow

### ISSUE THREAD

**Issue by lukdumi** [CeON/CoAnSys#364]
The setting distinctor.min.occurrences is never set to a value bigger than 1, so removing the node will speed up the hashing process.

**Comment by matfed** [comment]
I don't know what have you changed since I left, but as far as I remember this node also makes sure there are no duplicated documents/citations, and some following nodes fail if there are any dups.

**Comment by lukdumi** [comment]
Hi, nice to 'see' you :-)
Thanks for the info, we're going to leave it as it is then. We haven't changed much yet - the main change has been done in the heuristic workflow - we've merged the first 3 nodes into one in order for the workflow to run faster #352.
